### ISSUE TITLE
Add internationalization and localization support to readme

### ISSUE THREAD

**Issue by ryanoasis** [ryanoasis/nerd-fonts#118]
### Localization of readme.md

Translate and add localization of readme.md

#### Completed Translations:

* [x] Russian (@magauran via PR #203)
* [x] Simplified Chinese (@hiby90hou via PR #214)
* [x] Traditional Chinese (zh-TW) (Taiwan) (@MindyTai via PR #222)
* [x] French (@pgrimaud via PR #251)
* [x] Polish (@P1X3L0V4 via PR #301)
* [x] Spanish (@Tamh via PR #378)
* [x] Korean (@ParkSB via PR #382)
* [x] Japanese (@delphinus via PR #389)
* [x] Ukrainian (@igavelyuk via PR #392)
* [x] Italian (@JGiola via PR #427)
* [x] Portugal Portuguese (pt-pt) (@LiTO773 via PR #431)
* [x] Hindi (@HarshalRathore via PR #707)

#### Suggested Translation:

* [ ] Arabic
* [ ] Bengali
* [ ] ... Any other suggestions welcomed ...

**Comment by Magauran** [comment]
I'm working on a Russian translation

**Comment by ryanoasis** [comment]
@Magauran That'd be awesome! 😄 . I know we get quite a bit of Russian speaking visitors.

Let me know if you need anything from me.

**Comment by hiby90hou** [comment]
I can do Chinese translation

**Comment by ryanoasis** [comment]
@hiby90hou That would be great! Thanks! 😄 
Let us know if you need anything.

**Comment by cy91244** [comment]
I can do Traditional Chinese(zh-tw) translation if you like.
Most Taiwanese and Hong Kongese would much rather read in Traditional Chinese.

**Comment by Billy4195** [comment]
@ryanoasis The current readme_cn.md is written in `Simplified Chinese`, I stand for @cy91244 to add a `Traditional Chinese` version. :smile:

**Comment by ryanoasis** [comment]
@cy91244 That'd be great. I am all for this :smile: 

@Billy4195 Yeah. I agree. Thank you :smile:

**Comment by MindyTai** [comment]
@ryanoasis  I've finished a README of Traditional Chinese version on PR #222 !

**Comment by cy91244** [comment]
@MindyTai thanks for doing it.

**Comment by P1X3L0V4** [comment]
I'm working on Polish translation

**Comment by P1X3L0V4** [comment]
Finished Polish translation >> #301

**Comment by trinhminhhieu** [comment]
I'm working on a Vietnamese translation

**Comment by Tamh** [comment]
I'm working on a Spanish (generic) translation. Hopefully it will be compatible with Spain and Latin American variations.

**Comment by ryanoasis** [comment]
@trinhminhhieu @Tamh Great, thanks! Let us know if you have any questions or need any assistance.

**Comment by Tamh** [comment]
> 
> 
> @trinhminhhieu @Tamh Great, thanks! Let us know if you have any questions or need any assistance.

Finished the Spanish translation! #378

**Comment by tiagohermano** [comment]
I'll be working on a Brazillian Portuguese(PT-BR) translation, hopefully it will work for Portugal Portuguese as well.

**Comment by delphinus** [comment]
I'm working for Japanese translation on #389 👍

**Comment by RudrakshK** [comment]
I am working on Hindi translation.

**Comment by LiTO773** [comment]
Hi 👋. I did the Portugal Portuguese (pt-pt) translation. #431

**Comment by HarshalRathore** [comment]
**Hello** @ryanoasis, I'd like to suggest _Hindi_ localization for readme.md and if possible I'd like to work on it too.
Thank you for this awesome project.

**Comment by ryanoasis** [comment]
@HarshalRathore great suggestion. Would welcome it gladly. Thanks!

**Comment by HarshalRathore** [comment]
Hii @ryanoasis,
I recently found this awesome Github Action [dephraiim/translate-readme](https://github.com/dephraiim/translate-readme).
It translates the original readme.md to other languages on push to master branch. So if the original readme.md(the English version) is updated then localized version of it will also be updated, so users don't have to keep the other localised version of readme up to date.

It currently only supports translation from English to:-
- Chinese Simplified
- Chinese Traditional
- Hindi
- Arabic
- French

I know it is not much but at least these localized readmes maintenance will be automated.

The only thing is it can't auto-correct itself if there are any grammatical mistakes in the original(English version) of readme.

I wish to implement this method for the project.

**Comment by ryanoasis** [comment]
Hey @HarshalRathore merged your work and updated the description in this ticket to show that Hindi has been done.

That action is a great find and a good idea. Now that we are starting to have more action workflows I may have to play around with that, especially since the readme has changed quite a bit since the first few translations.

Thanks!

**Comment by Finii** [comment]
Transmuting this into a **The Future** milestone
